# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ax_pb2 as proto_dot_ax__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/ax_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentServiceStub(object):
    """AgentService defines the gRPC service for agent communication.
    This protocol enables a bidirectional communication between the
    controller and the agent. Agents can start new agentic calls via
    the controller within the same execution boundary by using the channel.

    WARNING: There will be significant changes to this protocol as
    we are solidifying resumption on the wire.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connect = channel.stream_stream(
                '/ax.AgentService/Connect',
                request_serializer=proto_dot_ax__pb2.AgentMessage.SerializeToString,
                response_deserializer=proto_dot_ax__pb2.AgentMessage.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/ax.AgentService/HealthCheck',
                request_serializer=proto_dot_ax__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=proto_dot_ax__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class AgentServiceServicer(object):
    """AgentService defines the gRPC service for agent communication.
    This protocol enables a bidirectional communication between the
    controller and the agent. Agents can start new agentic calls via
    the controller within the same execution boundary by using the channel.

    WARNING: There will be significant changes to this protocol as
    we are solidifying resumption on the wire.
    """

    def Connect(self, request_iterator, context):
        """Connect is used by agents to connect to the controller.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """HealthCheck checks if the agent is healthy and responsive
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Connect': grpc.stream_stream_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=proto_dot_ax__pb2.AgentMessage.FromString,
                    response_serializer=proto_dot_ax__pb2.AgentMessage.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=proto_dot_ax__pb2.HealthCheckRequest.FromString,
                    response_serializer=proto_dot_ax__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ax.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ax.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService(object):
    """AgentService defines the gRPC service for agent communication.
    This protocol enables a bidirectional communication between the
    controller and the agent. Agents can start new agentic calls via
    the controller within the same execution boundary by using the channel.

    WARNING: There will be significant changes to this protocol as
    we are solidifying resumption on the wire.
    """

    @staticmethod
    def Connect(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/ax.AgentService/Connect',
            proto_dot_ax__pb2.AgentMessage.SerializeToString,
            proto_dot_ax__pb2.AgentMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ax.AgentService/HealthCheck',
            proto_dot_ax__pb2.HealthCheckRequest.SerializeToString,
            proto_dot_ax__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ControllerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Exec = channel.unary_stream(
                '/ax.ControllerService/Exec',
                request_serializer=proto_dot_ax__pb2.ExecRequest.SerializeToString,
                response_deserializer=proto_dot_ax__pb2.ExecResponse.FromString,
                _registered_method=True)
        self.RegisterAgent = channel.unary_unary(
                '/ax.ControllerService/RegisterAgent',
                request_serializer=proto_dot_ax__pb2.RegisterAgentRequest.SerializeToString,
                response_deserializer=proto_dot_ax__pb2.RegisterAgentResponse.FromString,
                _registered_method=True)


class ControllerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Exec(self, request, context):
        """Exec executes an agentic task or resumes an existing one with streaming responses
        If the conversation_id already exists, it will be resumed.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterAgent(self, request, context):
        """RegisterAgent registers a new agent with the controller
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControllerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Exec': grpc.unary_stream_rpc_method_handler(
                    servicer.Exec,
                    request_deserializer=proto_dot_ax__pb2.ExecRequest.FromString,
                    response_serializer=proto_dot_ax__pb2.ExecResponse.SerializeToString,
            ),
            'RegisterAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterAgent,
                    request_deserializer=proto_dot_ax__pb2.RegisterAgentRequest.FromString,
                    response_serializer=proto_dot_ax__pb2.RegisterAgentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ax.ControllerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ax.ControllerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ControllerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Exec(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ax.ControllerService/Exec',
            proto_dot_ax__pb2.ExecRequest.SerializeToString,
            proto_dot_ax__pb2.ExecResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ax.ControllerService/RegisterAgent',
            proto_dot_ax__pb2.RegisterAgentRequest.SerializeToString,
            proto_dot_ax__pb2.RegisterAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class EventLogServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_unary(
                '/ax.EventLogService/List',
                request_serializer=proto_dot_ax__pb2.ListRequest.SerializeToString,
                response_deserializer=proto_dot_ax__pb2.ListResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/ax.EventLogService/Delete',
                request_serializer=proto_dot_ax__pb2.DeleteRequest.SerializeToString,
                response_deserializer=proto_dot_ax__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.Fork = channel.unary_unary(
                '/ax.EventLogService/Fork',
                request_serializer=proto_dot_ax__pb2.ForkRequest.SerializeToString,
                response_deserializer=proto_dot_ax__pb2.ForkResponse.FromString,
                _registered_method=True)


class EventLogServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def List(self, request, context):
        """List conversational events.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Deletes conversational events and all event log resources
        for its children executions.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Fork(self, request, context):
        """Fork forks an event log from a specific conversation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventLogServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=proto_dot_ax__pb2.ListRequest.FromString,
                    response_serializer=proto_dot_ax__pb2.ListResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=proto_dot_ax__pb2.DeleteRequest.FromString,
                    response_serializer=proto_dot_ax__pb2.DeleteResponse.SerializeToString,
            ),
            'Fork': grpc.unary_unary_rpc_method_handler(
                    servicer.Fork,
                    request_deserializer=proto_dot_ax__pb2.ForkRequest.FromString,
                    response_serializer=proto_dot_ax__pb2.ForkResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ax.EventLogService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ax.EventLogService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EventLogService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ax.EventLogService/List',
            proto_dot_ax__pb2.ListRequest.SerializeToString,
            proto_dot_ax__pb2.ListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ax.EventLogService/Delete',
            proto_dot_ax__pb2.DeleteRequest.SerializeToString,
            proto_dot_ax__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Fork(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ax.EventLogService/Fork',
            proto_dot_ax__pb2.ForkRequest.SerializeToString,
            proto_dot_ax__pb2.ForkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
